import { Institution, Student, Faculty, Group, Notice } from "@/types/institution";
import { StudentProfile } from "@/types/student";

export const DEMO_OTP = "123456";

export const registeredInstitutions: Institution[] = [
  {
    id: "inst-future-01",
    name: "Future Institute of Engineering and Management",
    type: "college",
    location: "Kolkata, West Bengal",
    website: "https://futurecollege.ac.in",
    logo: "🏛️",
    emailDomain: "@futurecollege.ac.in",
    studentIdPrefix: "SCH2026",
    adminName: "Dr. Alok Verma",
    adminEmail: "admin@futurecollege.ac.in",
    adminPhone: "+91 98300 12345",
    status: "active",
    createdAt: "2026-08-15",
  },
  {
    id: "inst-school-01",
    name: "Future Public School",
    type: "school",
    location: "Kolkata, West Bengal",
    website: "https://futurepublicschool.edu",
    logo: "🏫",
    studentIdPrefix: "SCH2026",
    adminName: "Mrs. Shobha Roy",
    adminEmail: "principal@futurepublicschool.edu",
    adminPhone: "+91 98311 54321",
    status: "active",
    createdAt: "2026-08-10",
  },
];

export const defaultInstitution: Institution = registeredInstitutions[0];

export const initialStudentProfiles: StudentProfile[] = [
  // College Demo Student
  {
    id: "stu-debendra",
    institutionId: "inst-future-01",
    institutionName: "Future Institute of Engineering and Management",
    institutionType: "college",
    name: "Debendra Bera",
    email: "debendra@futurecollege.ac.in",
    department: "Computer Science & Engineering",
    year: "1st Year",
    section: "A",
    rollNumber: "23",
    status: "active",
    accessType: "COLLEGE_EMAIL",
    interests: ["Programming", "AI & Machine Learning", "Web Development"],
    preferredStartTime: "6 PM",
    preferredEndTime: "10 PM",
    availableDailyHours: "2 hours",
    onboardingCompleted: true,
    joinedDate: "2026-08-01",
  },
  // School Demo Student
  {
    id: "stu-aarav",
    institutionId: "inst-school-01",
    institutionName: "Future Public School",
    institutionType: "school",
    name: "Aarav Sen",
    studentId: "SCH202600154",
    className: "Class 10",
    section: "B",
    rollNumber: "14",
    status: "active",
    accessType: "SCHOOL_STUDENT_ID",
    interests: ["Mathematics", "Computer Science", "Physics"],
    preferredStartTime: "5 PM",
    preferredEndTime: "8 PM",
    availableDailyHours: "2.5 hours",
    onboardingCompleted: true,
    joinedDate: "2026-08-01",
  },
  // Other college students
  {
    id: "stu-002",
    institutionId: "inst-future-01",
    institutionName: "Future Institute of Engineering and Management",
    institutionType: "college",
    name: "Priya Sharma",
    email: "priya.sharma@futurecollege.ac.in",
    department: "Computer Science & Engineering",
    year: "1st Year",
    section: "A",
    rollNumber: "12",
    status: "active",
    accessType: "COLLEGE_EMAIL",
    interests: ["Competitive Coding", "Data Structures"],
    preferredStartTime: "7 PM",
    preferredEndTime: "11 PM",
    availableDailyHours: "3 hours",
    onboardingCompleted: true,
    joinedDate: "2026-08-01",
  },
  {
    id: "stu-003",
    institutionId: "inst-future-01",
    institutionName: "Future Institute of Engineering and Management",
    institutionType: "college",
    name: "Rahul Mukherjee",
    email: "rahul.m@futurecollege.ac.in",
    department: "Computer Science & Engineering",
    year: "1st Year",
    section: "B",
    rollNumber: "65",
    status: "active",
    accessType: "COLLEGE_EMAIL",
    interests: ["Web Development", "UI/UX Design"],
    preferredStartTime: "6 PM",
    preferredEndTime: "9 PM",
    availableDailyHours: "2 hours",
    onboardingCompleted: false,
    joinedDate: "2026-08-01",
  },
];

export const initialStudents: Student[] = initialStudentProfiles.map((sp) => ({
  id: sp.id,
  institutionId: sp.institutionId,
  name: sp.name,
  email: sp.email,
  studentId: sp.studentId,
  department: sp.department,
  class: sp.className,
  year: sp.year,
  section: sp.section,
  rollNumber: sp.rollNumber,
  status: sp.status,
  joinedDate: sp.joinedDate,
}));

export const initialFaculty: Faculty[] = [
  {
    id: "fac-001",
    institutionId: "inst-future-01",
    name: "Dr. Ananya Sen",
    email: "ananya.sen@futurecollege.ac.in",
    department: "CSE",
    role: "Head of Department (HOD)",
    status: "active",
    joinedDate: "2020-07-15",
  },
  {
    id: "fac-002",
    institutionId: "inst-future-01",
    name: "Prof. Sourav Das",
    email: "sourav.das@futurecollege.ac.in",
    department: "CSE",
    role: "Associate Professor",
    status: "active",
    joinedDate: "2021-08-10",
  },
  {
    id: "fac-003",
    institutionId: "inst-future-01",
    name: "Dr. Amitava Roy",
    email: "amitava.roy@futurecollege.ac.in",
    department: "IT",
    role: "Professor & Academic Dean",
    status: "active",
    joinedDate: "2019-01-20",
  },
  {
    id: "fac-004",
    institutionId: "inst-future-01",
    name: "Prof. Meera Nair",
    email: "meera.nair@futurecollege.ac.in",
    department: "ECE",
    role: "Assistant Professor",
    status: "active",
    joinedDate: "2022-09-01",
  },
  {
    id: "fac-005",
    institutionId: "inst-future-01",
    name: "Dr. Subhash Chandra",
    email: "subhash.c@futurecollege.ac.in",
    department: "ME",
    role: "Head of Department (HOD)",
    status: "invited",
    joinedDate: "2026-08-18",
  },
];

export const initialGroups: Group[] = [
  {
    id: "grp-001",
    institutionId: "inst-future-01",
    name: "CSE • 1st Year • Section A",
    department: "CSE",
    year: "1st",
    section: "A",
    studentCount: 64,
    description: "First year Computer Science Section A cohort",
    createdAt: "2026-08-05",
  },
  {
    id: "grp-002",
    institutionId: "inst-future-01",
    name: "CSE • 1st Year • Section B",
    department: "CSE",
    year: "1st",
    section: "B",
    studentCount: 62,
    description: "First year Computer Science Section B cohort",
    createdAt: "2026-08-05",
  },
  {
    id: "grp-003",
    institutionId: "inst-future-01",
    name: "All CSE Students",
    department: "CSE",
    studentCount: 486,
    description: "All enrolled undergraduate students in Computer Science & Engineering",
    createdAt: "2026-08-01",
  },
  {
    id: "grp-004",
    institutionId: "inst-future-01",
    name: "All 1st Year Students",
    year: "1st",
    studentCount: 720,
    description: "All freshmen across CSE, IT, ECE, ME, and Civil streams",
    createdAt: "2026-08-01",
  },
  {
    id: "grp-005",
    institutionId: "inst-future-01",
    name: "All Students",
    studentCount: 2430,
    description: "Campus-wide student directory broadcast group",
    createdAt: "2026-08-01",
  },
];

export const initialNotices: Notice[] = [
  {
    id: "not-001",
    institutionId: "inst-future-01",
    title: "Scholarship Application 2026-27",
    content: "Merit-cum-means scholarship applications are open for 1st Year CSE students. Submit income certificate and grade card before the deadline.",
    targetGroup: "CSE • 1st Year",
    deadline: "10 September 2026",
    date: "02 Sep 2026",
    status: "published",
    recipientsCount: 486,
    category: "Scholarship",
  },
  {
    id: "not-002",
    institutionId: "inst-future-01",
    title: "Semester Examination Registration",
    content: "University exam form fill-up portal is live. Ensure tuition clearance and biometric verification before submission.",
    targetGroup: "All Students",
    deadline: "18 September 2026",
    date: "31 Aug 2026",
    status: "published",
    recipientsCount: 2430,
    category: "Academic",
  },
  {
    id: "not-003",
    institutionId: "inst-future-01",
    title: "Coding Club Orientation & Hackathon Kickoff",
    content: "Annual orientation for ACM / Developer Student Club and registration for Intra-College Hackathon 2026.",
    targetGroup: "CSE • All Years",
    deadline: "12 September 2026",
    date: "28 Aug 2026",
    status: "published",
    recipientsCount: 340,
    category: "Event",
  },
];
