import { Institution, Student, Faculty, Group, Notice } from "@/types/institution";
import { StudentProfile } from "@/types/student";

export const DEMO_OTP = "123456";

export const registeredInstitutions: Institution[] = [
  {
    id: "inst-future-01",
    name: "Future Institute of Engineering and Management",
    type: "college",
    location: "Kolkata, West Bengal",
    website: "https://futurecollege.ac.in",
    logo: "🏛️",
    emailDomain: "@futurecollege.ac.in",
    studentIdPrefix: "SCH2026",
    adminName: "Dr. Alok Verma",
    adminEmail: "admin@futurecollege.ac.in",
    adminPhone: "+91 98300 12345",
    status: "active",
    createdAt: "2026-08-15",
  },
  {
    id: "inst-school-01",
    name: "Future Public School",
    type: "school",
    location: "Kolkata, West Bengal",
    website: "https://futurepublicschool.edu",
    logo: "🏫",
    studentIdPrefix: "SCH2026",
    adminName: "Mrs. Shobha Roy",
    adminEmail: "principal@futurepublicschool.edu",
    adminPhone: "+91 98311 54321",
    status: "active",
    createdAt: "2026-08-10",
  },
];

export const defaultInstitution: Institution = registeredInstitutions[0];

export const initialStudentProfiles: StudentProfile[] = [
  // College Demo Student
  {
    id: "stu-debendra",
    institutionId: "inst-future-01",
    institutionName: "Future Institute of Engineering and Management",
    institutionType: "college",
    name: "Debendra Bera",
    email: "debendra@futurecollege.ac.in",
    department: "Computer Science & Engineering",
    year: "1st Year",
    section: "A",
    rollNumber: "23",
    status: "active",
    accessType: "COLLEGE_EMAIL",
    interests: ["Programming", "AI & Machine Learning", "Web Development"],
    preferredStartTime: "6 PM",
    preferredEndTime: "10 PM",
    availableDailyHours: "2 hours",
    onboardingCompleted: true,
    joinedDate: "2026-08-01",
  },
  // School Demo Student
  {
    id: "stu-aarav",
    institutionId: "inst-school-01",
    institutionName: "Future Public School",
    institutionType: "school",
    name: "Aarav Sen",
    studentId: "SCH202600154",
    className: "Class 10",
    section: "B",
    rollNumber: "14",
    status: "active",
    accessType: "SCHOOL_STUDENT_ID",
    interests: ["Mathematics", "Computer Science", "Physics"],
    preferredStartTime: "5 PM",
    preferredEndTime: "8 PM",
    availableDailyHours: "2.5 hours",
    onboardingCompleted: true,
    joinedDate: "2026-08-01",
  },
  // Other college students
  {
    id: "stu-002",
    institutionId: "inst-future-01",
    institutionName: "Future Institute of Engineering and Management",
    institutionType: "college",
    name: "Priya Sharma",
    email: "priya.sharma@futurecollege.ac.in",
    department: "Computer Science & Engineering",
    year: "1st Year",
    section: "A",
    rollNumber: "12",
    status: "active",
    accessType: "COLLEGE_EMAIL",
    interests: ["Competitive Coding", "Data Structures"],
    preferredStartTime: "7 PM",
    preferredEndTime: "11 PM",
    availableDailyHours: "3 hours",
    onboardingCompleted: true,
    joinedDate: "2026-08-01",
  },
  {
    id: "stu-003",
    institutionId: "inst-future-01",
    institutionName: "Future Institute of Engineering and Management",
    institutionType: "college",
    name: "Rahul Mukherjee",
    email: "rahul.m@futurecollege.ac.in",
    department: "Computer Science & Engineering",
    year: "1st Year",
    section: "B",
    rollNumber: "65",
    status: "active",
    accessType: "COLLEGE_EMAIL",
    interests: ["Web Development", "UI/UX Design"],
    preferredStartTime: "6 PM",
    preferredEndTime: "9 PM",
    availableDailyHours: "2 hours",
    onboardingCompleted: false,
    joinedDate: "2026-08-01",
  },
];

export const initialStudents: Student[] = initialStudentProfiles.map((sp) => ({
  id: sp.id,
  institutionId: sp.institutionId,
  name: sp.name,
  email: sp.email,
  studentId: sp.studentId,
  department: sp.department,
  class: sp.className,
  year: sp.year,
  section: sp.section,
  rollNumber: sp.rollNumber,
  status: sp.status,
  joinedDate: sp.joinedDate,
}));

export const initialFaculty: Faculty[] = [
  {
    id: "fac-001",
    institutionId: "inst-future-01",
    name: "Dr. Ananya Sen",
    email: "ananya.sen@futurecollege.ac.in",
    department: "CSE",
    role: "Head of Department (HOD)",
    status: "active",
    joinedDate: "2020-07-15",
  },
  {
    id: "fac-002",
    institutionId: "inst-future-01",
    name: "Prof. Sourav Das",
    email: "sourav.das@futurecollege.ac.in",
    department: "CSE",
    role: "Associate Professor",
    status: "active",
    joinedDate: "2021-08-10",
  },
  {
    id: "fac-003",
    institutionId: "inst-future-01",
    name: "Dr. Amitava Roy",
    email: "amitava.roy@futurecollege.ac.in",
    department: "IT",
    role: "Professor & Academic Dean",
    status: "active",
    joinedDate: "2019-01-20",
  },
  {
    id: "fac-004",
    institutionId: "inst-future-01",
    name: "Prof. Meera Nair",
    email: "meera.nair@futurecollege.ac.in",
    department: "ECE",
    role: "Assistant Professor",
    status: "active",
    joinedDate: "2022-09-01",
  },
  {
    id: "fac-005",
    institutionId: "inst-future-01",
    name: "Dr. Subhash Chandra",
    email: "subhash.c@futurecollege.ac.in",
    department: "ME",
    role: "Head of Department (HOD)",
    status: "invited",
    joinedDate: "2026-08-18",
  },
];

export const initialGroups: Group[] = [
  {
    id: "grp-001",
    institutionId: "inst-future-01",
    name: "CSE • 1st Year • Section A",
    department: "CSE",
    year: "1st",
    section: "A",
    studentCount: 64,
    description: "First year Computer Science Section A cohort",
    createdAt: "2026-08-05",
  },
  {
    id: "grp-002",
    institutionId: "inst-future-01",
    name: "CSE • 1st Year • Section B",
    department: "CSE",
    year: "1st",
    section: "B",
    studentCount: 62,
    description: "First year Computer Science Section B cohort",
    createdAt: "2026-08-05",
  },
  {
    id: "grp-003",
    institutionId: "inst-future-01",
    name: "All CSE Students",
    department: "CSE",
    studentCount: 486,
    description: "All enrolled undergraduate students in Computer Science & Engineering",
    createdAt: "2026-08-01",
  },
  {
    id: "grp-004",
    institutionId: "inst-future-01",
    name: "All 1st Year Students",
    year: "1st",
    studentCount: 720,
    description: "All freshmen across CSE, IT, ECE, ME, and Civil streams",
    createdAt: "2026-08-01",
  },
  {
    id: "grp-005",
    institutionId: "inst-future-01",
    name: "All Students",
    studentCount: 2430,
    description: "Campus-wide student directory broadcast group",
    createdAt: "2026-08-01",
  },
];

export const initialNotices: Notice[] = [
  {
    id: "not-001",
    institutionId: "inst-future-01",
    title: "Scholarship Application — Academic Year 2026",
    category: "Scholarship",
    priorityHint: "high",
    content: `All eligible first-year students are requested to complete the scholarship application process by September 10, 2026.

Students must submit the following documents:
1. Aadhaar Card
2. Previous Semester Marksheet
3. Income Certificate
4. Bank Account Details

Students who do not complete the process before the deadline may not be considered for the scholarship.

For assistance, contact the Student Welfare Office.`,
    targetType: "section",
    targetGroup: "CSE • 1st Year • Section A",
    targetDepartment: "CSE",
    targetYear: "1st Year",
    targetSection: "A",
    publicationDate: "2026-09-02",
    date: "02 Sep 2026",
    deadline: "September 10, 2026",
    eventDate: "2026-09-10",
    venue: "Student Welfare Office, Admin Block Room 104",
    status: "published",
    recipientsCount: 486,
    recipientCount: 486,
    createdBy: "Dr. Alok Verma (Registrar)",
    createdAt: "2026-09-02T10:00:00Z",
    publishedAt: "2026-09-02T10:05:00Z",
    attachmentName: "Scholarship_Guidelines_2026.pdf",
    attachmentType: "pdf",
    attachmentSize: "1.4 MB",
    aiAnalysisStatus: "ANALYZED",
    aiConfidence: 0.96,
    aiSummary: "Eligible first-year students must complete their scholarship application by September 10, 2026 and submit the required documents.",
    aiNoticeType: "SCHOLARSHIP",
    aiAnalysis: {
      summary: "Eligible first-year students must complete their scholarship application by September 10, 2026 and submit the required documents.",
      notice_type: "SCHOLARSHIP",
      audience: {
        departments: ["CSE"],
        years: ["1st Year"],
        classes: [],
        sections: ["A"],
      },
      dates: {
        publication_date: "2026-09-02",
        deadline: "2026-09-10",
        event_date: "2026-09-10",
        start_time: "10:00",
        end_time: "16:00",
      },
      requirements: [
        "Must be an eligible first-year student",
        "Complete and submit scholarship application before September 10, 2026",
      ],
      documents_required: [
        "Aadhaar Card",
        "Previous Semester Marksheet",
        "Income Certificate",
        "Bank Account Details",
      ],
      tasks: [
        {
          title: "Collect required documents",
          description: "Assemble Aadhaar Card, Marksheet, and Bank details.",
          deadline: "2026-09-08",
          estimated_minutes: 45,
        },
        {
          title: "Obtain income certificate",
          description: "Collect verified annual income certificate from competent authority.",
          deadline: "2026-09-07",
          estimated_minutes: 60,
        },
        {
          title: "Complete scholarship application",
          description: "Submit all verified documents and application form to the Student Welfare Office.",
          deadline: "2026-09-10",
          estimated_minutes: 30,
        },
      ],
      consequences: [
        "May not be considered for the scholarship if the application is not submitted before the deadline.",
      ],
      dependencies: [
        {
          blocked_task: "Complete scholarship application",
          required_task: "Obtain income certificate",
        },
      ],
      important_points: [
        "Applicable exclusively to eligible first-year students",
        "Strict action deadline is September 10, 2026",
        "Income certificate and academic marksheets are mandatory",
        "Assistance is available at the Student Welfare Office (Admin Block Room 104)",
      ],
      confidence: 0.96,
    },
  },
  {
    id: "not-002",
    institutionId: "inst-future-01",
    title: "End-Semester Examination Registration & Clearance",
    category: "Examination",
    priorityHint: "high",
    content: `University exam form fill-up portal is now open for all students. Ensure all library dues and laboratory clearance are completed prior to biometric registration.

Admit cards will only be generated after fee verification.`,
    targetType: "all",
    targetGroup: "All Students",
    publicationDate: "2026-08-31",
    date: "31 Aug 2026",
    deadline: "September 18, 2026",
    status: "published",
    recipientsCount: 2430,
    recipientCount: 2430,
    createdBy: "Exam Cell Controller",
    createdAt: "2026-08-31T09:30:00Z",
    publishedAt: "2026-08-31T09:45:00Z",
    attachmentName: "Exam_Schedule_Autumn2026.pdf",
    attachmentType: "pdf",
    attachmentSize: "2.1 MB",
  },
  {
    id: "not-003",
    institutionId: "inst-future-01",
    title: "Coding Club Orientation & Intra-College Hackathon 2026",
    category: "Event",
    priorityHint: "medium",
    content: `Annual orientation for ACM / Developer Student Club and registration kickoff for Intra-College Hackathon 2026. Win prizes worth ₹50,000 and direct internship interview fast-tracks.`,
    targetType: "department",
    targetGroup: "CSE • All Years",
    targetDepartment: "CSE",
    publicationDate: "2026-08-28",
    date: "28 Aug 2026",
    deadline: "September 12, 2026",
    eventDate: "2026-09-15",
    startTime: "10:00 AM",
    endTime: "05:00 PM",
    venue: "Main Auditorium & Computing Lab 3",
    status: "published",
    recipientsCount: 340,
    recipientCount: 340,
    createdBy: "Prof. Ananya Sen",
    createdAt: "2026-08-28T14:20:00Z",
    publishedAt: "2026-08-28T14:30:00Z",
  },
  {
    id: "not-004",
    institutionId: "inst-future-01",
    title: "Campus Wi-Fi Upgrade & Infrastructure Maintenance",
    category: "Administration",
    priorityHint: "low",
    content: `Scheduled maintenance on campus server room and high-speed fibre switches. Network access may experience intermittent latency from 11:00 PM to 04:00 AM.`,
    targetType: "all",
    targetGroup: "All Students",
    publicationDate: "2026-08-25",
    date: "25 Aug 2026",
    deadline: "August 26, 2026",
    status: "archived",
    recipientsCount: 2430,
    recipientCount: 2430,
    createdBy: "IT Infrastructure Team",
    createdAt: "2026-08-25T11:00:00Z",
    publishedAt: "2026-08-25T11:15:00Z",
  },
  {
    id: "not-005",
    institutionId: "inst-future-01",
    title: "AI & Machine Learning Guest Lecture by Google Research",
    category: "Academic",
    priorityHint: "medium",
    content: `Distinguished lecture on Transformers, Multimodal Foundation Models, and Agentic Reasoning systems by visiting scientists from Google DeepMind.`,
    targetType: "department",
    targetGroup: "CSE • 3rd & 4th Year",
    targetDepartment: "CSE",
    targetYear: "3rd Year",
    publicationDate: "2026-09-04",
    date: "04 Sep 2026",
    deadline: "September 08, 2026",
    status: "draft",
    recipientsCount: 210,
    recipientCount: 210,
    createdBy: "Dr. Alok Verma",
    createdAt: "2026-09-04T12:00:00Z",
  },
];

