import { Institution, Student, Faculty, Group, Notice } from "@/types/institution";

export const defaultInstitution: Institution = {
  id: "inst-future-01",
  name: "Future Institute of Engineering and Management",
  type: "college",
  location: "Kolkata, West Bengal",
  website: "https://futurecollege.ac.in",
  logo: "🏫",
  emailDomain: "@futurecollege.ac.in",
  studentIdPrefix: "SCH2026",
  adminName: "Dr. Alok Verma",
  adminEmail: "admin@futurecollege.ac.in",
  adminPhone: "+91 98300 12345",
  status: "active",
  createdAt: "2026-08-15",
};

export const initialStudents: Student[] = [
  {
    id: "stu-001",
    institutionId: "inst-future-01",
    name: "Debendra Bera",
    email: "debendra@futurecollege.ac.in",
    studentId: "SCH20260001",
    department: "CSE",
    year: "1st",
    section: "A",
    rollNumber: "CSE-26-001",
    status: "active",
    joinedDate: "2026-08-01",
  },
  {
    id: "stu-002",
    institutionId: "inst-future-01",
    name: "Priya Sharma",
    email: "priya.sharma@futurecollege.ac.in",
    studentId: "SCH20260002",
    department: "CSE",
    year: "1st",
    section: "A",
    rollNumber: "CSE-26-002",
    status: "active",
    joinedDate: "2026-08-01",
  },
  {
    id: "stu-003",
    institutionId: "inst-future-01",
    name: "Rahul Mukherjee",
    email: "rahul.m@futurecollege.ac.in",
    studentId: "SCH20260003",
    department: "CSE",
    year: "1st",
    section: "B",
    rollNumber: "CSE-26-065",
    status: "active",
    joinedDate: "2026-08-01",
  },
  {
    id: "stu-004",
    institutionId: "inst-future-01",
    name: "Sneha Roy",
    email: "sneha.roy@futurecollege.ac.in",
    studentId: "SCH20260004",
    department: "IT",
    year: "2nd",
    section: "A",
    rollNumber: "IT-25-014",
    status: "active",
    joinedDate: "2025-08-01",
  },
  {
    id: "stu-005",
    institutionId: "inst-future-01",
    name: "Ankit Das",
    email: "ankit.das@futurecollege.ac.in",
    studentId: "SCH20260005",
    department: "ECE",
    year: "3rd",
    section: "A",
    rollNumber: "ECE-24-033",
    status: "pending",
    joinedDate: "2024-08-01",
  },
  {
    id: "stu-006",
    institutionId: "inst-future-01",
    name: "Riya Sen",
    email: "riya.sen@futurecollege.ac.in",
    studentId: "SCH20260006",
    department: "CSE",
    year: "2nd",
    section: "B",
    rollNumber: "CSE-25-089",
    status: "active",
    joinedDate: "2025-08-01",
  },
  {
    id: "stu-007",
    institutionId: "inst-future-01",
    name: "Aman Gupta",
    email: "aman.gupta@futurecollege.ac.in",
    studentId: "SCH20260007",
    department: "ME",
    year: "1st",
    section: "A",
    rollNumber: "ME-26-008",
    status: "active",
    joinedDate: "2026-08-01",
  },
  {
    id: "stu-008",
    institutionId: "inst-future-01",
    name: "Tanvi Paul",
    email: "tanvi.paul@futurecollege.ac.in",
    studentId: "SCH20260008",
    department: "IT",
    year: "3rd",
    section: "B",
    rollNumber: "IT-24-045",
    status: "inactive",
    joinedDate: "2024-08-01",
  },
];

export const initialFaculty: Faculty[] = [
  {
    id: "fac-001",
    institutionId: "inst-future-01",
    name: "Dr. Ananya Sen",
    email: "ananya.sen@futurecollege.ac.in",
    department: "CSE",
    role: "Head of Department (HOD)",
    status: "active",
    joinedDate: "2020-07-15",
  },
  {
    id: "fac-002",
    institutionId: "inst-future-01",
    name: "Prof. Sourav Das",
    email: "sourav.das@futurecollege.ac.in",
    department: "CSE",
    role: "Associate Professor",
    status: "active",
    joinedDate: "2021-08-10",
  },
  {
    id: "fac-003",
    institutionId: "inst-future-01",
    name: "Dr. Amitava Roy",
    email: "amitava.roy@futurecollege.ac.in",
    department: "IT",
    role: "Professor & Academic Dean",
    status: "active",
    joinedDate: "2019-01-20",
  },
  {
    id: "fac-004",
    institutionId: "inst-future-01",
    name: "Prof. Meera Nair",
    email: "meera.nair@futurecollege.ac.in",
    department: "ECE",
    role: "Assistant Professor",
    status: "active",
    joinedDate: "2022-09-01",
  },
  {
    id: "fac-005",
    institutionId: "inst-future-01",
    name: "Dr. Subhash Chandra",
    email: "subhash.c@futurecollege.ac.in",
    department: "ME",
    role: "Head of Department (HOD)",
    status: "invited",
    joinedDate: "2026-08-18",
  },
];

export const initialGroups: Group[] = [
  {
    id: "grp-001",
    institutionId: "inst-future-01",
    name: "CSE • 1st Year • Section A",
    department: "CSE",
    year: "1st",
    section: "A",
    studentCount: 64,
    description: "First year Computer Science Section A cohort",
    createdAt: "2026-08-05",
  },
  {
    id: "grp-002",
    institutionId: "inst-future-01",
    name: "CSE • 1st Year • Section B",
    department: "CSE",
    year: "1st",
    section: "B",
    studentCount: 62,
    description: "First year Computer Science Section B cohort",
    createdAt: "2026-08-05",
  },
  {
    id: "grp-003",
    institutionId: "inst-future-01",
    name: "All CSE Students",
    department: "CSE",
    studentCount: 486,
    description: "All enrolled undergraduate students in Computer Science & Engineering",
    createdAt: "2026-08-01",
  },
  {
    id: "grp-004",
    institutionId: "inst-future-01",
    name: "All 1st Year Students",
    year: "1st",
    studentCount: 720,
    description: "All freshmen across CSE, IT, ECE, ME, and Civil streams",
    createdAt: "2026-08-01",
  },
  {
    id: "grp-005",
    institutionId: "inst-future-01",
    name: "All Students",
    studentCount: 2430,
    description: "Campus-wide student directory broadcast group",
    createdAt: "2026-08-01",
  },
];

export const initialNotices: Notice[] = [
  {
    id: "not-001",
    institutionId: "inst-future-01",
    title: "Scholarship Application 2026-27",
    content: "Merit-cum-means scholarship applications are open for 1st Year CSE students. Submit documents before deadline.",
    targetGroup: "CSE • 1st Year",
    deadline: "10 September 2026",
    date: "02 Sep 2026",
    status: "published",
    recipientsCount: 486,
    category: "Scholarship",
  },
  {
    id: "not-002",
    institutionId: "inst-future-01",
    title: "Semester Examination Registration",
    content: "University exam form fill-up portal is live. Ensure tuition clearance and biometric verification before submission.",
    targetGroup: "All Students",
    deadline: "18 September 2026",
    date: "31 Aug 2026",
    status: "published",
    recipientsCount: 2430,
    category: "Academic",
  },
  {
    id: "not-003",
    institutionId: "inst-future-01",
    title: "Coding Club Orientation & Hackathon Kickoff",
    content: "Annual orientation for ACM / Developer Student Club and registration for Intra-College Hackathon 2026.",
    targetGroup: "CSE • All Years",
    deadline: "12 September 2026",
    date: "28 Aug 2026",
    status: "published",
    recipientsCount: 340,
    category: "Event",
  },
];
